### ISSUE TITLE
failed to load source for a dependency on `redox_syscall`

### ISSUE THREAD

**Issue by Csega** [redox-os/redox#777]
Hi guy,

I see the following error for a few days. I thought it worth to mention it. Could you help me with this one?

Cheers!
Csega

**Reproduction**: Run the newest bootstrap.sh for a clean installation.

**Expected behavior**: compile and run the code

**Actual behavior**: after cloning and cd redox, the make all gives the following error:
    Updating git repository `https://github.com/redox-os/syscall.git`
error: failed to load source for a dependency on `redox_syscall`

Caused by:
  Unable to update https://github.com/redox-os/syscall.git

Caused by:
  failed to fetch into /home/my_user/.cargo/git/db/syscall-2a6b827678b57cba

Caused by:
  [16/-17] The SSL certificate is invalid
Makefile:352: recipe for target 'build/userspace/libstd.rlib' failed
make: *** [build/userspace/libstd.rlib] Error 101

**Build information**: rustc 1.15.0-nightly (28d6623bc 2016-12-03), git rev-parse HEAD: 7ee0ea3c861dd5b6709e4f0a723619618c356b21, qemu version: 2.5, Linux elementaryOS 4.4.0-51-generic #72-Ubuntu SMP Thu Nov 24 18:29:54 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bjorn3** [comment]
Please update cargo. Known problem of cargo. See rust-lang/cargo#3340.

**Comment by jackpot51** [comment]
This has been fixed if you update your nightly

**Comment by Csega** [comment]
Thanks for the answers. Sorry for the stupid question, but how can I update cargo? I did a quick google for it, but I only found rustup update and cargo update, which did not update cargo, the version is still the same: cargo 0.16.0-nightly (3568be9 2016-11-26).

Or maybe there is no solution to this problem until now (based on this thread: https://github.com/rust-lang/cargo/issues/3340), or is it just not implemented in rustup yet? I'm getting confused.

**Comment by jackpot51** [comment]
You can also fix this by running `export SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt` before building

**Comment by bjorn3** [comment]
`rustup update` also updates cargo.

**Comment by Csega** [comment]
Thanks, it works now! :)
